# -*- coding: utf-8 -*-
"""Auto-build a compact ENUM value-map for the SQL agent (BIRD-style evidence / M-Schema values).

Discovers low-cardinality text columns across DIM_*/FACT_*/v_*/pos_logs/ocr_warranty_form, lists their
distinct values, merges a tiny hand-curated overlay for semantics the data can't reveal (rank order,
code->meaning), and writes `fahmai/tools/enum_dict.py` (a committed `ENUM_CARD` string — no DB hit at
import). Re-run after a data reload.

Run:  uv run python scripts/build_enum_dictionary.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from sqlalchemy import text

from fahmai.db import ROOT, get_engine

ENUM_MAX = 15          # a column counts as an enum if it has <= this many distinct values
VALUE_MAXLEN = 45      # truncate long values (e.g. the batch-defect claim_reason strings)
TABLE_RE = re.compile(r"^(dim_|fact_|v_|pos_logs|ocr_warranty_form)")
SKIP_COL = re.compile(r"_id$|_code$|_number$|name|email|phone|path|content|title|summary|"
                      r"participant|description|_th$|_en$|tracking|counterparty", re.I)
_NUMERICISH = re.compile(r"^[\d.\-/ ]+$")   # all-numeric value set -> a quantity/id, not a semantic enum
OUT = ROOT / "fahmai" / "tools" / "enum_dict.py"

# --- tiny hand-curated overlay: semantics NOT present in the data ---
ORDERINGS = {
    "loyalty_tier": "rank low->high: silver < gold < platinum (none = no tier). Use CASE, never max().",
    "position_level": "rank low->high: IC < Manager < Director < C-level.",
    "msrp_tier": "price tier (low->high): budget/mass < mid < premium/flagship (verify exact labels).",
}
CODE_MEANINGS: dict[str, str] = {
    # "col": "A=..., B=..."  (add if a code column needs decoding)
}


def candidate_columns(conn) -> list[tuple[str, str]]:
    rows = conn.execute(text("""
        select table_name, column_name
        from information_schema.columns
        where table_schema = 'public'
          and data_type in ('text','character varying','character','varchar','char')
        order by table_name, ordinal_position
    """)).fetchall()
    out = []
    for t, c in rows:
        if not TABLE_RE.match(t):
            continue
        if SKIP_COL.search(c):
            continue
        out.append((t, c))
    return out


def distinct_values(conn, table: str, col: str) -> list[str] | None:
    """Return sorted distinct values if the column is an enum (<= ENUM_MAX), else None."""
    try:
        rows = conn.execute(text(
            f'select distinct "{col}" from "{table}" where "{col}" is not null limit {ENUM_MAX + 1}'
        )).fetchall()
    except Exception:
        return None
    if len(rows) > ENUM_MAX:
        return None
    vals = sorted(str(r[0]) for r in rows)
    return [v if len(v) <= VALUE_MAXLEN else v[:VALUE_MAXLEN] + "…" for v in vals]


def main() -> int:
    engine = get_engine()
    # group identical (column, value-set) across tables so shared enums (brand_family, category,
    # transaction_type in both fact_* and v_*) collapse to ONE line listing the tables.
    groups: dict[tuple, list[str]] = {}
    with engine.connect() as conn:
        for table, col in candidate_columns(conn):
            vals = distinct_values(conn, table, col)
            if not vals or len(vals) < 2:                  # skip constants / empties
                continue
            if all(_NUMERICISH.match(v) for v in vals):    # all-numeric -> not a semantic enum
                continue
            groups.setdefault((col, tuple(vals)), []).append(table)

    lines = []
    for (col, vals), tables in sorted(groups.items()):
        note = ""
        if col in ORDERINGS:
            note = f"  [{ORDERINGS[col]}]"
        elif col in CODE_MEANINGS:
            note = f"  [{CODE_MEANINGS[col]}]"
        tbls = ", ".join(sorted(tables))
        lines.append(f"- {col} ({tbls}): " + " | ".join(vals) + note)
    n_cols = len(lines)

    body = "\n".join(lines)
    card = ("# ENUM VALUES & ORDERINGS (auto-generated; values verbatim, [..] = domain note)\n"
            "# For 'highest/lowest' over a ranked text column, use the stated rank — do NOT alphabetical-max.\n"
            + body)
    OUT.write_text(
        "# -*- coding: utf-8 -*-\n"
        '"""Auto-generated by scripts/build_enum_dictionary.py — do not edit by hand."""\n\n'
        "ENUM_CARD = r'''" + card + "'''\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT}: {n_cols} enum columns, {len(card)} chars")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
